### PR TITLE
A couple of fixes

### PR DESCRIPTION
**Pull request by dapetcu21**
* Fix `screenshot.png()` callback returning raw pixels
* Fix memory leak and improve error handling

### CODE REVIEW

**Review by britzl — APPROVED** [review]
Looks good. Thank you!

**Comment by britzl** [comment]
Fixes #15

**Comment by dapetcu21** [comment]
@britzl Did you mean to merge this? I think you just closed it without merging.

**Comment by britzl** [comment]
Fixed!

**Comment by britzl** [comment]
> Fixed!

What the?! Gimme a sec.

**Pull request merged**
